### ISSUE TITLE
Getting Authentication Error in dev-portal after some idle time

### ISSUE THREAD

**Issue by piraveena** [wso2/identity-apps#1045]
**Describe the Issue:**
After some idle time developer portal redirects to this authentication error page.

![image](https://user-images.githubusercontent.com/17597293/86091071-e798d580-bac8-11ea-9b1e-5093fd22a5ce.png)

**How To Reproduce:**
5.11. m25 pack

- Access developer-portal
- Keep it idle for some time

Redirects to this page: https://devcloud.kubesb.com/authenticationendpoint/retry.do?sp=Developer+Portal&tenantDomain=carbon.super

**Comment by brionmario** [comment]
@vihanga-liyanage Shall we look in to this?

**Comment by thivi** [comment]
Resolved by #1054
