### ISSUE TITLE
Browser / UI scaling issue- User portal

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/identity-apps#113]
**Describe the bug**
UI Issue after  minimizing the Browser 

Screenshot attached:
![image](https://user-images.githubusercontent.com/39120228/68853007-05165c00-06ff-11ea-8fea-5175aa438ee2.png)

**Test Environment** 
  - Product IS : wso2is-5.10.0-m4
  - Browser : Safari- Version 13.0.3 (13608.3.10.10.1), Google Chrome Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by thivi** [comment]
I am working on this issue.

**Comment by thivi** [comment]
This issue has been fixed. Now, when the screen width is less than or equal to 600px, a dropdown appears instead of tabs. 
![image](https://user-images.githubusercontent.com/20745428/70967652-d6ecb900-20bc-11ea-9ed1-333529b054e7.png)

**Comment by jeradrutnam** [comment]
@NilukaSripalim Can you please verify and close the issue? Thanks

**Comment by NilukaSripalim** [comment]
Retested in DEV- identity-apps-0.1.152-SNAPSHOT

![image](https://user-images.githubusercontent.com/39120228/70973600-f5a67c00-20cb-11ea-8f38-9b3d413a9404.png)
