### ISSUE TITLE
When non admin user is login there are errors in the console

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/identity-apps#131]
**Describe the bug**
If you log in using non-admin user security page is not loading properly

**To Reproduce**
1. Sign in using non-admin user
2. Go to the security page

**Expected behavior**
Flow should work without any issues

**Screenshots**
![image](https://user-images.githubusercontent.com/17597685/69234785-0095eb80-0bb6-11ea-83ec-f134c7689058.png)

**Comment by jeradrutnam** [comment]
Fixed in #171
