### ISSUE TITLE
Unable to list "Personal info" when a  user(SCIM2.0) create with  multi valued attribute

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/identity-apps#133]
Type/BUG
Affected/5.10.0
Severity/Major
Priority/High

**Screenshots attached**
Response comparing 
![image](https://user-images.githubusercontent.com/39120228/69237091-e27eba00-0bba-11ea-9dc6-004deb2eb670.png)

SCIM 2.0 REST API
curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"jackson","givenName":"kim"},"userName":"kim","password":"kimwso2","emails":[{"primary":true,"value":"kim.jackson@gmail.com","type":"home"},{"value":"kim_j@wso2.com","type":"work"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users

**Comment by NipuniBhagya** [comment]
This will be fixed with the refactoring of the profile info section using the profile meta details.
