### ISSUE TITLE
Mistake- "WSO2 Identity Server Privacy Policy" web page

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/identity-apps#141]
Please follow the attached document: ( issues are highlighted)

https://docs.google.com/document/d/17WeJPSUOzDf8kf8woSNZmKZxqVmQ1MPfu2xzYr74f_A/edit

**Comment by thivi** [comment]
"organisation" was replaced with "organization" in this commit:
https://github.com/wso2/identity-apps/commit/5557e5f52da5502a2bc04027543836b2ab1f32f3
