### ISSUE TITLE
UI issue with, User portal Consent page

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/identity-apps#160]
Tested Environment: **wso2is m8**  DEV mode

Please refer attached screenshots :

Issue 1:
![image](https://user-images.githubusercontent.com/39120228/69789821-4d497a00-11e7-11ea-9724-bd449be543b6.png)

Issue 2:
Select,  "Select All" then it will only select the particular checkbox. 
![image](https://user-images.githubusercontent.com/39120228/69790026-ac0ef380-11e7-11ea-8a30-076eb522e7bc.png)

Issue3:
 Asterisk (*) symbol which uses for identity mandatory fields should be red color.
![image](https://user-images.githubusercontent.com/39120228/69791459-98b15780-11ea-11ea-8b8a-fb08420f2bd2.png)

Issue 4 : Environment -**windows 2016 server, Google chrome browser**
When click on "Continue" without selecting any radio button

![image](https://user-images.githubusercontent.com/39120228/70130151-0b687a00-16a6-11ea-94a6-a7618d620078.png)

**Comment by jeradrutnam** [comment]
Except issue 1 & 2 are already fixed. Will close the issue once other 2 also fixed.
