### ISSUE TITLE
Getting an Error and unable to  add  a biometric device via user portal

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/identity-apps#161]
Tested Environment: wso2is m8, Dev mode, 
Browsers: **Google**-Version 78.0.3904.108 (Official Build) (64-bit) and **Firefox** 70.0.1 (64-bit)

**Description**
Getting an error, when trying to add  a biometric device via User portal
 "Error occurred while retrieving the device"

:9443/api/users/v1/me/webauthn/start-registration?appId=https:%2F%2Flocalhost:9000:1 GET https://localhost:9443/api/users/v1/me/webauthn/start-registration?appId=https:%2F%2Flocalhost:9000 500

Added below in identity.xml j2
"<FIDO>
        <WebAuthn>
            <Enable>{{fido.webauthn.enable}}</Enable>
        </WebAuthn>
        <FIDO2TrustedOrigins>
            {% for origin in fido.trusted.origins %}
                <Origin>{{origin}}</Origin>
                <Origin>https://localhost:9000/</Origin>
                <Origin>https://localhost</Origin>
            {% endfor %}
        </FIDO2TrustedOrigins>
    </FIDO>
"

**Comment by NipuniBhagya** [comment]
We can close this issue as this is fixed in the latest IS version. However, the API endpoint will be changed in the next version (from v1 to v2) and therefore will be changing the user portal implementation accordingly once the changes are merged in the server-side.

**Comment by jeradrutnam** [comment]
Fixed by #250
