### ISSUE TITLE
Translating display names of claims

### ISSUE THREAD

**Issue by thivi** [wso2/identity-apps#192]
**Is your feature request related to a problem? Please describe.**
The label of the claims in the profile page don/t support translation.

**Describe the solution you'd like**
Since the profile page obtains the label to be displayed for claims from the displayName attribute of the schema attributes, translated versions of the display names should be available to support localization.

**Comment by darshanasbg** [comment]
IMO, we should have localization capability unified across the component\portal..

As `Display Name` is a custom property which does not defined in the SCIM Schema Definition, it would be better to use `name` as the i18n key and use it to show localized display name and use `Display Name` only as backup mechanism if we cannot resolve the value.

**Comment by thanujalk** [comment]
+1 for the approach...
We may need escape spaces in the display names with "\" in the file as this going to be the key.

**Comment by darshanasbg** [comment]
Name attribute don't have white spaces as it follow camel case.

**Comment by thivi** [comment]
This PR resolves this issue: https://github.com/wso2/identity-apps/pull/203
