### ISSUE TITLE
Styling issues in the login page when federated idps are added

### ISSUE THREAD

**Issue by darshanasbg** [wso2/identity-apps#207]
**Describe the bug**
$subject. Built a product on top of https://github.com/wso2/product-is/commit/d0302d07f024a9299d3ee84a633efa0f839ce6bc.
 
<img width="504" alt="Screen Shot 2019-12-13 at 3 26 55 PM" src="https://user-images.githubusercontent.com/1617810/70791593-62b0cd80-1dbd-11ea-9120-eea2e4f32ba8.png">

**To Reproduce**
1. Create two idps.
2. Edit "User Portal" service provider. Click on "Local & Outbound Authentication Configuration" section. Click on "Advanced Configuration" option button.
3. Add created two idps as login options.
4. Click update.
5. Try to login to user portal SP.

If you add basic authentication in step 3 above, it would looks like following,
<img width="525" alt="Screen Shot 2019-12-13 at 4 48 43 PM" src="https://user-images.githubusercontent.com/1617810/70796521-7c0b4700-1dc8-11ea-9d1d-164bfc012a52.png">

**Comment by thivi** [comment]
I had to remove the class `labeled` from the button element to make sure the button label is center-aligned properly.
![image](https://user-images.githubusercontent.com/20745428/70800409-3489b880-1dd2-11ea-932f-14ef741b5be5.png)

**Comment by darshanasbg** [comment]
If we don't have basic authentication then we shouldn't have that separator (the one with "OR")

**Comment by jeradrutnam** [comment]
> If we don't have basic authentication then we shouldn't have that separator (the one with "OR")

Yes, need to handle it. Will do.

**Comment by darshanasbg** [comment]
@thivi: Have we fixed the above issue? If so can you close the issue.

**Comment by jeradrutnam** [comment]
Yes, this fixed.

**Comment by jeradrutnam** [comment]
Fixed: "OR" divider showing when basic authentication UI is not there https://github.com/wso2/identity-apps/pull/225

![image](https://user-images.githubusercontent.com/7569427/70974692-6058b700-20ce-11ea-81ff-090a3a9f7005.png)
