### ISSUE TITLE
i18n not working properly

### ISSUE THREAD

**Issue by darshanasbg** [wso2/identity-apps#210]
Refer the image below,
<img width="1275" alt="Screen Shot 2019-12-14 at 2 39 57 PM" src="https://user-images.githubusercontent.com/1617810/70846535-2abe8e80-1e80-11ea-96ef-47a806d126f7.png">
characters in other languages not showing properly.

Note the text `WSO2 Identity Server Â© 2019` in the left side of footer, it also have weird charactor.

**Comment by darshanasbg** [comment]
Similar character issue is also present with the notifications messages as well. Refer below image,
<img width="439" alt="Screen Shot 2019-12-15 at 10 19 07 AM" src="https://user-images.githubusercontent.com/1617810/70858236-70cd2e00-1f24-11ea-91df-904bcb3a8a16.png">

**Comment by brionmario** [comment]
The default encoding type in jsp is not UTF-8. This causes issues when rendering special characters. PR #219 should fix this issue.
