### ISSUE TITLE
Remove User Portal app showing in the user-portal

### ISSUE THREAD

**Issue by darshanasbg** [wso2/identity-apps#211]
Note below image, `User Portal` app showing in the application list page.

<img width="888" alt="Screen Shot 2019-12-14 at 1 10 26 PM" src="https://user-images.githubusercontent.com/1617810/70846579-986aba80-1e80-11ea-8581-b451a9dcc30e.png">

**Comment by jeradrutnam** [comment]
We have added a fix from client side. Which check for application name and hide the app from listing. But user can change this value from Admin Console, an then this will break and user needs to update the changed application name in runtime config in user portal application.

Added an issue in product-is to track the back-end support. https://github.com/wso2/product-is/issues/7142
