### ISSUE TITLE
Application listing inconsistencies 

### ISSUE THREAD

**Issue by darshanasbg** [wso2/identity-apps#212]
Note the below image,

---
<img width="937" alt="Screen Shot 2019-12-14 at 2 56 13 PM" src="https://user-images.githubusercontent.com/1617810/70846698-eb913d00-1e81-11ea-8661-94b6910a9b62.png">

When there are mix of applications,
* Ones that have a description and
* Ones that doesn't have description

it can see following issues,
1. `Recent Application` section has an inconsistency with the size of tiles
2. `All Application` section also has the same consistency as above which is only visible when hover over the mouse pointer on different applications
3. Description is not properly showing in the application listing. Have to revisit on how to show the description in there.
4. In `All Application` section, in applications that does not have descriptions, the application name seems to be more positioned towards the top, compared to ones that have the descriptions.

**Comment by darshanasbg** [comment]
@madurangasiriwardena: Were you referring one of the four issues listed above? If not can you please add it also here.

**Comment by madurangasiriwardena** [comment]
@darshanasbg, yes, I'm reffing to the issue number 1.

**Comment by brionmario** [comment]
I'm working on this issue.

**Comment by brionmario** [comment]
PR #227 should solve this issue.
