### ISSUE TITLE
Need to update styling on all OOTB shipped endpoints

### ISSUE THREAD

**Issue by darshanasbg** [wso2/identity-apps#214]
**Is your feature request related to a problem? Please describe.**

Tried SMS OTP flow where I have basic authenticator as the step 1 and SMS OTP IDP as the step 2.

Step-1 basic login page looks like this,
<img width="535" alt="Screen Shot 2019-12-15 at 10 44 40 AM" src="https://user-images.githubusercontent.com/1617810/70864186-bf56e880-1f75-11ea-8d04-40607cab3887.png">
while the step-2 SMS OTP page looks like this,
<img width="628" alt="Screen Shot 2019-12-15 at 8 02 52 PM" src="https://user-images.githubusercontent.com/1617810/70864208-eb726980-1f75-11ea-9549-75a315f7cff1.png">

Cannot have disconnected UX, hence as the first iteration it should have all the OOTB shipped endpoints to use same styling pattern.

As of 5.10.0-m9, following endpoints are available OOTB.
```
accountrecoveryendpoint
authenticationendpoint
emailotpauthenticationendpoint
smsotpauthenticationendpoint
totpauthenticationendpoint
user-portal
x509certificateauthenticationendpoint
```

Then should have a plan to update all other endpoints that product supports.

**Comment by jeradrutnam** [comment]
Yes, we need to move smsotpauthenticationendpoint, emailotpauthenticationendpoint, x509certificateauthenticationendpoint also to this repo.

**Comment by darshanasbg** [comment]
We need to think whether its need these as all separate endpoints, rather having all authentication related endpoints included in the `authenticationendpoint`.

**Comment by jeradrutnam** [comment]
> We need to think whether its need these as all separate endpoints, rather having all authentication related endpoints included in the `authenticationendpoint`.

Yes, I think we can do it in login-portal development effort. So these endpoints will replace by it.

**Comment by darshanasbg** [comment]
I'm thinking to get this done for the 5.10.0 itself..

**Comment by jeradrutnam** [comment]
> I was thinking to address this more short term, like 5.10.0 itself..

Let's have a chat. Need to check with other priorities right?

**Comment by jeradrutnam** [comment]
@thivi has styled the endpoints. And currently those are there has separate endpoints. So we will track merging them together with a separate issue: https://github.com/wso2/identity-apps/issues/281
