### ISSUE TITLE
When SCIM not enabled for the user-store user-portal goes to an inconsistent state after the login.

### ISSUE THREAD

**Issue by thanujalk** [wso2/identity-apps#216]
**Describe the bug**
When SCIM not enabled for the user-store user-portal goes to an inconsistent state after the login.

**To Reproduce**
1. Create a secondary user-store.
2. Create a user and add the required roles.
3. Login to the user-portal.
4. We can see the inconsistent state as in the screenshot.

**Expected behavior**
The user-portal should relay on the id_token for user attributes and disable any features which use the SCIM.

**Screenshots**
<img width="1149" alt="Screenshot 2019-12-16 at 10 42 15" src="https://user-images.githubusercontent.com/1498339/70880959-f0283380-1ff0-11ea-97c2-f84f9f1789f9.png">

**Comment by thanujalk** [comment]
Related - https://github.com/wso2/product-is/issues/7103

**Comment by brionmario** [comment]
I'm working on this issue.

**Comment by brionmario** [comment]
PR #227 should fix this issue. SCIM disabled users will be directed to the login error page will be asked to login with a different account.
