### ISSUE TITLE
Profile completion showed as not complete, even all values are given

### ISSUE THREAD

**Issue by darshanasbg** [wso2/identity-apps#221]
**Describe the bug**
`Mobile` claim showing a `Incomplete Claim` even it have a value.

**To Reproduce**
1. Login to user portal
2. Fill all profile attributes. See below image,
<img width="938" alt="Screen Shot 2019-12-17 at 8 19 12 AM" src="https://user-images.githubusercontent.com/1617810/70960839-27a4e780-20a6-11ea-8309-4f7c8a9669e4.png">

3. Go to overview page. It shows `Mobile` claim as `Incomplete Claim`
<img width="553" alt="Screen Shot 2019-12-17 at 8 19 22 AM" src="https://user-images.githubusercontent.com/1617810/70960831-207dd980-20a6-11ea-882c-355d3637fa26.png">

**Environment**
A product-is m10-snapshot pack with identity-apps: 0.1.149.

**Comment by brionmario** [comment]
I'm working on this issue.

**Comment by brionmario** [comment]
PR #227 should solve this issue.
