### ISSUE TITLE
Claim names are not translated in profile completion component

### ISSUE THREAD

**Issue by darshanasbg** [wso2/identity-apps#222]
**Describe the bug**
<img width="607" alt="Screen Shot 2019-12-17 at 8 22 53 AM" src="https://user-images.githubusercontent.com/1617810/70961036-b74a9600-20a6-11ea-8447-2fe1bd6a3329.png">

Claims are get translated in the Profile page though,
<img width="936" alt="Screen Shot 2019-12-17 at 8 25 56 AM" src="https://user-images.githubusercontent.com/1617810/70961113-e8c36180-20a6-11ea-8e5f-42d62829689f.png">

Additionally, lets get URL and other possible claims also translated by default. So if anyone enabled supported by default for OOTB claims shipped in the product, usability be intact.

**Environment**
A product-is m10-snapshot pack with identity-apps: 0.1.149.

**Comment by brionmario** [comment]
I'm working on this issue.

**Comment by brionmario** [comment]
#227 should solve this issue.
