### ISSUE TITLE
Associating users who does not have login permission

### ISSUE THREAD

**Issue by thanujalk** [wso2/identity-apps#223]
**Describe the bug**
From the user-portal, we can associate users who do not have login permission. Then when we try to switch to that user, user-portal goes to the logout page. 

**Expected behavior**
The current behavior is somewhat ok, but we can improve the experience in the following ways,
- Do not allow the association of the user accounts which do not have login permission?
- Since the permission later can be removed, during the switch time if the required scopes did not get returned, switch back to the previous account showing a warning message?

**Comment by darshanasbg** [comment]
Do not allow the association of the user accounts which do not have login permission?

**Comment by darshanasbg** [comment]
> **Describe the bug**
> From the user-portal, we can associate users who do not have login permission. Then when we try to switch to that user, user-portal goes to the logout page.
> 
> **Expected behavior**
> The current behavior is somewhat ok, but we can improve the experience in the following ways,
> 
> * Do not allow the association of the user accounts which do not have login permission?

Not allowing to associate based on permission is wrong IMO.. We should allow to associate.

> * Since the permission later can be removed, during the switch time if the required scopes did not get returned, switch back to the previous account showing a warning message?
If possible, showing the account switch related actions should be disabled. So user don't have a way to try switching to different account in user portal they don't have access.

**Comment by thanujalk** [comment]
Now there is no permission validation for APIs consumed by User-Portal. So,  any user can log in to the User_Portal.
