### ISSUE TITLE
Page will navigate to empty page-Self-registration 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/identity-apps#231]
Affected IAM version : 5.10 m9
Identity -app version : 0.1.152-SNAPSHOT
Type: Improvement
Severity: Medium 
Priority: High

**Description**
After filling in all the data and clicking on the "Register", it will move to an empty page.

Expected improvement : 
it is better if we can display a conformation message box 
EX: **Confirmation link has been sent to your email**

**Comment by thivi** [comment]
This PR #244 resolves this issue.
