### ISSUE TITLE
The cancel does not redirect to the "Sign in" page when clicked

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/identity-apps#232]
Affected Version:
-IAM version:  5.10 m9
- Identity -app version - 0.1.152-SNAPSHOT

- Type: Bug
-Severity: Medium
- Priority : High

**Description**
The consent page does not redirect to the home page when clicking on cancel.

**Tested Environment:**
 - OS: macOS
 - Browser Chrome, Firefox

**Comment by thanujalk** [comment]
User portal will receive the following response, 
https://localhost:9443/user-portal/login?error_description=User+denied+the+consent&error=access_denied&sp=User%2BPortal&tenantDomain=carbon.super

Then as Identity Server has an IdP session, we need to send the authorization request with prompt=login to allow user to reauthenticate with a different user.

**Comment by thivi** [comment]
This issue has been resolved by #243
