### ISSUE TITLE
The mobile number is provided but it is not updated in the "optional fields completed" section

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/identity-apps#233]
Affected Version:
-IAM version: 5.10 m9
-Identity -app version - 0.1.152-SNAPSHOT
-Type: Bug
-Severity: Medium
-Priority : High

**Description **

Either user created with mobile number, via management console or
the mobile number updated via user portal,  it is not updated in the "Complete your profile"->"optional fields completed" section

**Test Environment**
 - OS: Mac OS
 - Browser Chrome, Firefox

**Comment by brionmario** [comment]
This issue was already reported(#221) and it should be fixed with the PR #227

**Comment by NilukaSripalim** [comment]
Duplicated.
