### ISSUE TITLE
Profile claims are not synced with Personal info

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/identity-apps#239]
Affected version: is_5 10 m9, -Identity -app version - 0.1.152-SNAPSHOT

**Description**
Default user Profile (management console) claims are not synced with Personal info-> user profile claims.

**
management console,  by using wso2 http://wso2.org/claims, but in user profile get claims through scim dialect, so this may be the cause of this issue.

**Comment by thivi** [comment]
This #240 PR resolves this issue.

**Comment by jeradrutnam** [comment]
@NilukaSripalim Please verify the fix and close the issue.
