### ISSUE TITLE
User able to Register user and will get email confirmation message without checking "Privacy Policy" checkbox

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/identity-apps#274]
**Description**

User able to Register user and will get email confirmation message without checking "Privacy Policy" checkbox

Scenario: Self user registration -> Create New Account (https://localhost:9443/accountrecoveryendpoint/signup.do)

Step to reproduce:
Enter all required fields,  and try to click Register without checking "I hereby confirm that I have read and understood the Privacy Policy"

**Comment by jeradrutnam** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/286

**Comment by NilukaSripalim** [comment]
Affected version: wso2is-5.10.0-alpha3-SNAPSHOT
Identity -app : 0.9.11-SNAPSHOT

With the current implementation,  I try with, the same scenario by checking the "I hereby confirm that I have read and understood the Privacy Policy" application does not allow me to "Register " ,

I tried by filling all the fields as well only filling mandatory, and checked privacy policy,
but when I clicked the "Register" it popup an error message -"Please confirm that you have read and understood the Privacy Policy"

With this issue, self-registration is blocking.

**Comment by NilukaSripalim** [comment]
The fix is affected in ( #286) , wso2is-5.10.0-alpha3 and tested and verified, working as expected in wso2is-5.10.0-alpha3(latest- 4-2-2020 released)
