### ISSUE TITLE
Even password does not match with Confirm password, user can successfully register  

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/identity-apps#275]
Affected IS version: wso2is-5.10.0-alpha2-SNAPSHOT
Identity App: 0.9.8-SNAPSHOT

**Description**
Scenario: self user registration 
Even password does not match with Confirm password, user can successfully register.

Step to reproduced:
Enable Self User Registration - Identity Providers > Resident and expand the Account Management Policies section.(management Console)
2. Click on "Create Account" in user portal
3. Add proper user name and click on Proceed to self Register
4. Fill fields which required, in "Create New Account" section
5. **enter that, Password != Confirm password**
6. Click Register

Application allow user to continue, process even password != conform password

**Comment by jeradrutnam** [comment]
https://github.com/wso2/identity-apps/pull/286
