### ISSUE TITLE
Application display invalid confirmation message when enter the non existing  user name

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/identity-apps#289]
**Description**
Step to reproduce: 
**Forgot password use case** Login screen user portal
Initially, Management Console
1. Configure the email configurations in deployment.toml
    [output_adapter.email]
from_address= "<email_address>"
username="<username-email adress>"
password="<passord>"

2. Click on Resident found under the Identity Providers section on the Main tab of the management console.
3.  Expand the Account Management Policies tab, then the Account Recovery tab and select the Enable Notification Based Password Recovery. 

In User portal,
Click on the Forgot password link and enter a non-existing user name, select the "Recover with Email" option and submit it.

Then, the Application display an invalid confirmation message

Please refer screenshots :
1. 
![image](https://user-images.githubusercontent.com/39120228/72748687-e9877000-3bdd-11ea-962e-2144faed2de5.png)

2. 
![image](https://user-images.githubusercontent.com/39120228/72748733-12a80080-3bde-11ea-8755-3e3a3abd89df.png)

Expected Behaviour: if the user enters the non-existing or invalid or deleted user name then there should be a display validation message for “Invalid username” or “User not exist.”

**Additional context**
But there is proper Error log is displaying in wso2carbon log

ERROR {org.wso2.carbon.identity.recovery.endpoint.impl.RecoverPasswordApiServiceImpl} - Unable to find an user with username: Nonexistentuser in the system.

**Comment by thanujalk** [comment]
Having this change will allow external parties to identify user names in the Identity Server. So the current behavior is correct.
