### ISSUE TITLE
Cross-Site Scripting vulnerability in uglifyjs-webpack-plugin plugin

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/identity-apps#300]
**Describe the bug**
`npm audit` report will give a moderate security vulnerability for the webpack plugin `uglifyjs-webpack-plugin` which has an outdated dependency `serialize-javascript` in it's dependency list.

[Vulnerability Report](https://www.npmjs.com/advisories/1426)

**To Reproduce**
1. Go to the root of ìdentity-app` repository.
2. Run command `npm audit` to get the report.

**Expected behavior**
The `npm audit` command shouldn't have any vulnerabilities listed.

**Screenshots**
<img width="836" alt="Screenshot 2020-01-24 at 11 44 02" src="https://user-images.githubusercontent.com/11191791/73048542-89275580-3e9f-11ea-83cd-978f5f0e40ad.png">

**Desktop (please complete the following information):**
 - OS: MacOs Catelina
 - Browser: N/A
 - Version: N/A

**Comment by thivi** [comment]
Looks like this plugin's repo has been archived. It is better to replace this plugin with Terser[1][2]. 

[1] https://github.com/webpack-contrib/terser-webpack-plugin
[2] https://github.com/webpack-contrib/terser-webpack-plugin/issues/15

**Comment by jeradrutnam** [comment]
Fixed: https://github.com/wso2/identity-apps/pull/301
