### ISSUE TITLE
Remember me option on sign-in page / login page not working-user portal

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/identity-apps#313]
Tested version: identity-app: 0.9.17-SNAPSHOT
**Describe the bug**
1. Login as admin/ admin by selecting "Remember me on this computer" option
2. sign out
3. enter password as "admin"

Issue: "Remember me" is  not working in user portal

Need to look in how this can be implemented in a secure manner.

**Comment by thanujalk** [comment]
Tested and worked as expected.
