### ISSUE TITLE
User portal allow user to successfully login, when  user don't have even Login permission

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/identity-apps#319]
Affected version: 
IS- wso2is-5.10.0-alpha3-SNAPSHOT 
Identity app: 0.9.21-SNAPSHOT

**Describe the bug**
The newly created user who don't have login permission,  but though the user portal the user can successfully login.

**To Reproduce**
1. Create a new user, (Testuser) 
2. Only assign the role, Internal/everyone but don't have any permission 
3. Try to login with the user portal, with a correct user name, password
4. user can successfully login to user portal

**Expected behavior**
If the user doesn't have login permission then system should not allow the user to login to the user portal.

**Comment by thanujalk** [comment]
@NilukaSripalim  Current behavior is the expected behavior.  For user-portal, you don't need to have any permission.
