### ISSUE TITLE
[user-portal] Unable view Consent in "Security > Manage consents"

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/identity-apps#376]
Tested Environment :
is: wso2is-5.10.0-alpha3 & wso2is-5.10.0-alpha4 snapshot 
identity app: 0.9.24-SNAPSHOT
MAC O/S google chrome 

**Describe the bug**
Unable to view Consents, in "Security > Manage consents", but user already added conent while login to the user portal

**To Reproduce**
1. Go to 'Management console' and untick "Skip Login Consent" -> Service providers > User portal > Local & Outbound Authentication Configuration
2. Login to the user portal via https://localhost:9443/user-portal with admin credentials
3. Select all the consents (select all "Requested attributes") and Continue  
4. Unable to view Consents, in "Security > Manage consents"

**Comment by thanujalk** [comment]
This is fixed now.
