### ISSUE TITLE
Observing 403 Forbidden from Cloud Developer Portal when the browser is idle for sometime

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/identity-apps#959]
**Suggested Labels**
Priority/Highest
Severity/Critical
Type/Bug

**How To Reproduce:**
1. Login to developer portal in dev cloud as tenant
https://devcloud.kubesb.com/t/iam.com/developer-portal

2. Keep the browser window idle for sometime

**Observation**
Observing 403 Forbidden from the browser and browser remains logged out as below image with tenant domain appended 2 times for the logout URL

![UI2](https://user-images.githubusercontent.com/31848014/84863725-09d73000-b093-11ea-858d-fc8e0a7dff79.png)

Logout URL Observed
https://devcloud.kubesb.com/t/iam.com/t/iam.com/developer-portal/logout

**Comment by vihanga-liyanage** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/961
