### ISSUE TITLE
Error log in Firefox browser console-User Portal

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/identity-apps#99]
IAM Product : wso2is-5.10.0-m3
Priority : Low
Severity : Low

**Describe the bug**
When click on the "Logout" button,  error logs are displayed in **Firefox browser console**

**To Reproduce**
1. Login with proper credentials 
2. Scroll down to. 'user-dropdown'
3.  Click on 'Logout' button
4. See error in console

**Expected behavior**
User should successfully logout without any error.

**Screenshots**
![image](https://user-images.githubusercontent.com/39120228/68015738-db9a1100-fcb8-11e9-84da-50cacd9d9afe.png)

![image](https://user-images.githubusercontent.com/39120228/68015745-e05ec500-fcb8-11e9-9ad6-7a8d5f2f6c08.png)

![image](https://user-images.githubusercontent.com/39120228/68015766-eb195a00-fcb8-11e9-9f18-31be6f6cf9f0.png)

 - OS: Mac OS , Windows-Server-2016-standard-64bit
 - Browser Firefox 70.0 (64-bit) & 70.0.1 (64-bit

**Comment by thivi** [comment]
This issue has been resolved. 
![image](https://user-images.githubusercontent.com/20745428/70967624-c2102580-20bc-11ea-883b-1f5a652fa2e4.png)

**Comment by jeradrutnam** [comment]
@NilukaSripalim Can you please verify and close the issue? Thanks

**Comment by NilukaSripalim** [comment]
working as expected, Retested in DEV- identity-apps-0.1.152-SNAPSHOT
